### ISSUE TITLE
Support multi-aliasing

### ISSUE THREAD

**Issue by ccazette** [jonathangeiger/kohana-jelly#11]
As discussed on this thread : http://forum.kohanaphp.com/comments.php?DiscussionID=4713. (see my posts and banks replies)

'name' => new Field_String('name'),
'alternate-name' => 'name',

Would work so that it doesn't matter if you get/update alternate-name or name, it would always deal with 'name'. That's the neatest implementation we could find in that thread. Currently if you want several aliases, you have to create several Fields, so your model is getting bloated and updating soon gets messy...

**Comment by jonathangeiger** [comment]
Sounds good. I will implement this soon.

**Comment by jonathangeiger** [comment]
Fixed with 0bad214068419031e238b4fe642c0c2295dca60b.

Fields can now be aliased to other fields. This is also completely transparent (just as column aliasing is). It works for all parts of Jelly, including setting, getting, saving, joining, etc.

I will update the documentation tomorrow and then close this ticket.

A few implementation details I will note here as well as in the docs:
- Aliased fields are not in your $model->meta()->fields list. This is expected.

This should not be relied up however:
- Aliases are stored in $model->meta()->aliases, which is an array. The keys of the array are then names of the aliases, and the values of these keys is the column they point to. 

Theoretically, you should be able to set aliases in two separate ways, should you find one syntax cleaner than the other (although the documented way will be what you proposed)
1. The way you proposed...

Or (in your initialize())

```
$meta->aliases += array(
     'alias' => 'field',
);
```
