### ISSUE TITLE
Configurable input element id attributes

### ISSUE THREAD

**Issue by leth** [jonathangeiger/kohana-jelly#116]
There are the two commits in my fork which address this. Let me know if they need further work before they can be merged.
I've also forked the test repo to fix the tests this breaks.
Cheers

**Comment by banks** [comment]
Thanks leth. We are rather snowed under with bugs, patches and features we intend to implement so we will review this when we get a chance. Please don't take the delay as a sign that we don't appreciate your contribution though!

I'll mark this as low priority because it is not 'fix' as such and we are primarily focussed on implementing road-mapped features and making the API stable.

I'm sure as soon as one of us gets a chance to look we will be able to merge easily.

**Comment by leth** [comment]
Thanks for the update. :)

**Comment by jonathangeiger** [comment]
Don't think we'll be incorporating this since I'm planning on removing input() by 1.0 anyway. Thanks for your help though leth.

**Comment by leth** [comment]
Fair enough! Formo looks like it's coming along nicely for this sort of thing :)
