### ISSUE TITLE
Setting DB for all the models

### ISSUE THREAD

**Issue by glamorous** [jonathangeiger/kohana-jelly#34]
Is it possible to set DB-variable for all models instead of doing this for every model in the meta? What I mean is:

A way to set the default DB for all your models (now 'default' hard written in the core)
A way to override this per model (like the API already support)

Why?

It's handy if all the models take the 'default'-db if the environment is IN_PRODUCTION and the 'local' when not.. Now I'm not sure where I can do/set this.

**Comment by banks** [comment]
> It's handy if all the models take the 'default'-db if the environment is IN_PRODUCTION and the 'local' when not.. Now I'm not sure where I can do/set this.

Most people would simply have a different DB config for 'default' between the two invoronments. The whole point of config files is that you don't have to put special cases in code when you move between different platforms etc as it is all in the config.

I'm not sure I really see a case for this - you should have your default DB set up differently on the two environments, either with different config files (that aren't added to your version control for the project) or with code that automatically sets the correct config based on the environment.

If you really want to use a non-standard set up and have a different 'default'. `Jelly_Meta` is transparently extendable - extend it in your app and put whatever logic you want in. There is no point in making every class transparently extendible like we have if we then go and support every edge case in config anyway!

I'm closing this as I feel we already provide enough flexibility to do what you want in a satisfactory way - Jon, if you feel this is worth adding then feel free to overrule me but I feel this takes us closer and closer to a monolithic configure-everything type solution rather than a lean, cleanly-extensible-if-you-don't-like-the-defaults solution.

**Comment by glamorous** [comment]
Ok, no problem :) that's pretty clear.. So you suggest that I should have an if-clause with IN_PRODUCTION in my db config that's returning the config array with both 'default'? That's sounds good enough for me

**Comment by banks** [comment]
> So you suggest that I should have an if-clause with IN_PRODUCTION

Yep, or just use different config files on each server and exclude them from your repo.

I would also recommend using Kohana::$environment rather than a defined constant. This is the preferred way in KO3.

**Comment by glamorous** [comment]
Like found here: http://kerkness.ca/wiki/doku.php?id=setting_up_production_environment

I was used to IN_PRODUCTION and saw it in the example-bootstrap from "wingsc" http://github.com/shadowhand/wingsc/blob/master/application/bootstrap.php so I thought that was the way to go... Thanks for the info!

Is there something security-related wrong with IN_PRODUCTION?

**Comment by banks** [comment]
> Is there something security-related wrong with IN_PRODUCTION?

No it is just less flexible - you are either in production of not. With environment you can have as many different 'environments' as you like.
