### ISSUE TITLE
'0' or '' (empty) values not in query.

### ISSUE THREAD

**Issue by manact** [jonathangeiger/kohana-jelly#47]
Values of 0 are not set for Field_Integer
Values of '' (empty) are not set for Field_String
=> in the final query

Model :
        $meta->table('tests')
            ->fields(array(
            'id' => new Field_Primary,
            'test_name' => new Field_String,
            'ord' => new Field_Integer
        ));
Controller
            $post['test_name'] = 'a name for the this test';
            $post['ord'] = '0';
            $test = Model::factory('test')
                ->set(array(
                'test_name' => $post['test_name'],
                'ord' => $post['ord'],
            ))->save();

Query
INSERT INTO `tests` (`test_name`) VALUES ('a name for the this test') (1)

The same occurs if I try to update a record and set the test_name to '' (empty) and the name is actually test3 in the database with id of 5.
Controller
            $post['test_name'] = '';
            $post['ord'] = '0';
            $test = Model::factory('test')
                ->set(array(
                'test_name' => $post['test_name'],
                'ord' => $post['ord'],
            ))->save(5);
Query
No query at all.

**Comment by manact** [comment]
No query for this one too.
Based on the same model :
if test_name is set to '' (empty) and ord is set to '5' for update id 5.
Database
        'id' = '5';
        'test_name' = 'a name for the this test';
        'ord' = '1';
Controller
        $post['test_name'] = '';
        $post['ord'] = '5';
        $test = Model::factory('test')
            ->set(array(
            'test_name' => $post['test_name'],
            'ord' => $post['ord'],
        ))->save(5);
Query
No query.

**Comment by jonathangeiger** [comment]
Values should be considered for exclusion from being changed only when the original is different from the default. Closed by bd765b679c8b95df139d7cc49779ca4aa0d70230. Thanks for the detailed report manact.

Here's a detailed explanation of what went wrong:

This is kind of complicated to explain, but here goes:

If you want to update or insert a model without first loading it, when setting the data, Jelly does a non-strict (==) comparison between the new value and the current value.

This gets around issue #16 (which, after working on this, I've realized needs to be re-opened). When you set a unique field to the same value it is currently set to, the above behavior ensures that it's not counted as changed and thus validated (erroneously) to be unique.

That's all fine, but the non-strict comparison doesn't work for setting things to 0 and empty strings and such. Those things end up not counting as changes when they should (because we're comparing to the default for the field which defaults to NULL). The fix, then, is to check that the original value is not equal to the default (so we can tell whether or not we're changing).

**Comment by manact** [comment]
Many thanks for the detailed explanation.
I'm sorry to ping-pong this to #16 but I'm allright with this fix till I'll have no unique key to deal with at this time.
I will try to help if I can.

**Comment by jonathangeiger** [comment]
No worries. The fix doesn't actually _break_ #16, your example just made me realize that #16 wasn't entirely fixed in the first place. I posted a comment on it over there if you're interested.
