### ISSUE TITLE
get() should return FALSE [Actually it shouldn't but should throw an exception]

### ISSUE THREAD

**Issue by ccazette** [jonathangeiger/kohana-jelly#69]
I think Jelly_Model::get() should return FALSE if no valid property are matched. 

It currently returns NULL but as you may have fields returning NULL, this may be confusing as you end up having no way to tell if your property is valid but the value is NULL, or if no field was matched... Perhaps (not sure about this) magic get() should take this into account and not setting _retrieved if get() returns FALSE...

Don't you think ?

**Comment by banks** [comment]
Not sure. We'll think about this. You may also have fields returning FALSE so this is not really fixing the problem just moving it. I'm not convinced it is a problem thought. If something isn't defined I feel NULL is the appropriate response. If you need to check if a property is valid you should probably just query the meta object directly. That won't work for additional fields but I feel this is becoming enough of an edge case not to warrant changing the core. you can always write a method to manually check if a property points to an actual DB value or not if this is really necessary.

I'll leave this open for Jon to look over but my inclination is that NULL is semantically the correct response and get() is not the correct way to determine if a property is valid. In ambiguous cases.

**Comment by ccazette** [comment]
Fair enough, but then unless I am missing something what would you use to check you can actually get() something ? You may want to get an alias, a field, a relationship, or unmapped database column that is in your table when you use that method. It basically tries everything to return something matching the given parameter.
There is no method I can think of that would do such thing... You would have to check in the key is in meta()->fields then in meta()->aliases, then if your model is instantiated in $model->_unmapped, not even saying that most of them is protected...

As I said, I might miss something obvious, but I am in the situation where if I want to check a property is somehow valid, $model->get() is the only method around that tries everything...

**Comment by banks** [comment]
Hmmm. Why do you need to know this? I can see the problem and if there is a real need to be able to tell if a property is valid it's probably best to a method like `valid()` to `Jelly_Model` which returns Boolean indicating that the property is known.

I guess I find it hard to know why you might need this. I can't think of an example now where I would have different logic is a property was valid or if it returned NULL. I guess there are some but I'd like to establish whether there is a case for implementing a solution for this or whether it would be best just to leave it to the developer. If you can give us an example where it is important to be able to distinguish in practice that would help.

Another alternative would be to throw an exception if it gets to the end of `get()` without finding a suitable property. Perhaps this is a better plan generally. Thoughts?

**Comment by ccazette** [comment]
Here's an example : trying to implement a REST module, user can query specific fields using a GET parameter. He doesn't know at all what query will be generated, so he just asks for fields like name, gender, date_of_birth, about_me, address... Thing is some of these fields are defined in model_user, some in model_profile or some in model_address. So first I have to know at some point which model to join with() given the requested fields, and then when looping through the results, I have to know if I have to run $user->get($field), or $user->profile->get($field) or $user->address->get($field) etc etc...

Another thing is that if you ask for $model->something_that_does_not_exist, using the magic get, it will use the get() method and will cache something_that_does_not_exist into the model in _retrieved. I am not sure that's bad, though...

Throwing an exception doesn't seem like a bad idea... TBH, I would understand if you choose not to change anything, as I would find a workaround. I just wanted to share my thoughts as I encountered this problem...

**Comment by banks** [comment]
OK, thanks for that. I think in your case get() returning is only part of the problem - you still need to work out which model etc. which would never be automatic. In other words you'll need to write custom code to achieve what you want any way so there is not much argument to accomodate this specifically.

That said, having thought a little bit about this, I feel that throwing an exception _is_ a good idea. I'm not sure it would directly benefit your situation though.

Jon, what so you think about this idea. We can turn this into a todo if you thing this is a good idea.

**Comment by jonathangeiger** [comment]
What about isset?

**Comment by ccazette** [comment]
Mmmh... isn't isset using magic get ? Then that would be the same since magic get uses a get() under the hood...

**Comment by banks** [comment]
> What about isset?

isset considers a NULL value unset. @ccazette wants to be able to distinguish between genuine properties with a NULL value and undefined properties.

**Comment by SpadXIII** [comment]
You could use the magic __isset method and return a TRUE/FALSE accordingly

**Comment by ccazette** [comment]
@SpadXIII: Doh, I missed the magic isset function... Anyway, I know there are workarounds I could use by extending the model (you could always extend it to make it work as you wish), the question is more : does it makes sense to have get() returning an Exception ?
I'd say yes... That would also prevent caching fields that do not exist in the model when using magic get.

**Comment by SpadXIII** [comment]
I think that throwing an exception would be better than just returning NULL, as NULL could also indicate a value.

@ccazette: you could extend the model by specifying a magic __isset() yourself, but I think it should also be implemented within Jelly. That way, you could use `$model->isset('fieldname')` with your REST-models instead of catching exceptions.

**Comment by banks** [comment]
@SpadXIII: I'm not convinced about isset() magic or otherwise. In PHP this happens:

```
$var = NULL; // Var is explicitly set to NULL
var_dump(isset($var)); // Will give boolean FALSE
```

You see PHP isset considers NULL to mean not set (which in actual fact is _exactly_ what it means). What is being discussed here is actually more like 'is this property defined' rather than 'is this property set'.

I think implementing non-standard behaviour in a magic __isset method or in a normal method called isset() is semantically wrong and will confuse people. NULL is not just another value it is explicitly the value or a variable or property that is not set.

**Comment by SpadXIII** [comment]
Adding a magic __isset() method doesn't mean anything else has to change. This method just returns a TRUE/FALSE instead of a value (NULL or other)

But after thinking about it some more, I think you're correct banks. You could do an easy check `isset($model->field)` anywhere. If the field is not set, __get would return NULL meaning isset will give FALSE. This is cached within the model. Speeding up following calls.
No real need for isset or exceptions in the core.

**Comment by banks** [comment]
> Adding a magic __isset() method doesn't mean anything else has to change.

Not sure what you mean here. Sure __isset() returns a bool, my point is that the bool SHOULD by FALSE even for a valid field if that field has the value NULL since that is what isset() does. Which mens it is identical to `is_null($model->field)` and isn't what the OP wants...

> No real need for isset or exceptions in the core.

I still possibly see an argument for throwing an exception as it will make it possible to determine if a property is valid (rather than is non-NULL). Just try accessing it and catch any exception. It may also help with debugging complex code...

**Comment by jonathangeiger** [comment]
I'm deferring this for a future revision since a consensus hasn't been reached. Currently, isset() returns TRUE or FALSE only if the field is defined; it doesn't care if it's NULL or not.

**Comment by banks** [comment]
I didn't realise that was how it currently works. In that case you are right and the OP could use isset() to determine if a property was valid regardless of it's value.

This is inconsistent with PHP's isset() and with the definition of NULL generally but I'm not sure I'm all that bothered either way. We should make a note to document this properly and I'll close this for now and re-open or revisit later if it actually causes problems for people.

**Comment by jonathangeiger** [comment]
> This is inconsistent with PHP's isset() and with the definition of NULL generally but I'm not sure I'm all that bothered either way

I'm not bothered either.
