### ISSUE TITLE
Enum Field

### ISSUE THREAD

**Issue by ginad** [jonathangeiger/kohana-jelly#84]
if there is a validation error the enum field doesn't return or select the previews selected item.

ex. 

```
"role"=> new Field_Enum(array(
    "choices"=>array(""=>"select","admin"=>"Administrator","client"=>"Client"),
    "rules"=> array("not_empty"=>NULL)
))
```

in keeps returning a validation error even if you select one.

**Comment by jonathangeiger** [comment]
You're not setting your enum properly. An enumerated list has numeric keys, not string keys. It should be something like:

```
"choices"=>array("admin", "client"),
```

**Comment by ginad** [comment]
still having error. i think its because the $value in the set() function is the key not the actual value.

```
/**
 * If $value is in the $choices array, then it is used, otherwise $default is used
 *
 * @param   mixed  $value
 * @return  mixed
 */
public function set($value)
{       
    if (in_array($value, $this->choices))
    {
        return $value;
    }
    else
    {
        if ($this->null AND empty($value))
        {
            return NULL;
        }

        return $this->default;
    }
}
```

**\* it should be  ***

```
/**
 * If $value is in the $choices array, then it is used, otherwise $default is used
 *
 * @param   mixed  $value
 * @return  mixed
 */
public function set($value)
{
    if (!array_key_exists($value, $this->choices))
            {
        if ($this->null AND empty($value))
        {
            $value =  NULL;
        }

        $value = $this->default;
    }
            return $value;
}
```

using assoc array in the choices allows you to customize the value to be returned.

ex.
"choices"=>array("male","female","others")  this will return 0,1,2 what if you want to store M,F,O in the database instead?

"choices"=>array("m"=>"male","f"=>"female","o"=>"others")

**Comment by jonathangeiger** [comment]
> "choices"=>array("male","female","others") this will return 0,1,2 what if you want to store M,F,O in the database instead?

Then you should declare it as

```
"choices"=>array("m", "f", "o"),
```

This is exactly how the ENUM datatype works, which is what this field emulates. You have a list of values and when you pass a value in that list it's changed. You don't pass the keys.

**Comment by banks** [comment]
@jonathan, I think what ginad is confuse dby is he wants to store 'm', 'f', 'o' in the Database, but wants to display 'Male', 'Female' or 'Other' in the select box in the form.

I guess the answer at the moment is that You have to build the select manually for this to work - the choices array in the field object is only ever DB values and if you want different display values, you should store them somewhere else.

That said, I think @ginad's usage _should_ work. I think enum fields should support the current usage OR key => value usage where the array keys are the database values. How easy it is to make both work happily I don't know.

Perhaps say that integer keys are assumed to indicate that it is just values whereas string keys indicate key => value. If you wanted key => value with numbers going into the db you could still do it like:

```
'0' => 'None',
'1' => 'One,
```

**Comment by ginad** [comment]
I tried this: "choices"=>array("a","b","c") and selected "b" then modified the set() function to print the value being passed:

<pre>
/**
 * If $value is in the $choices array, then it is used, otherwise $default is used
 *
 * @param   mixed  $value
 * @return  mixed
 */
public function set($value)
{       
   $found = "no";
   $original_value = $value;
    if (in_array($value, $this->choices))
    {
        $found = "yes";
    }
    else
    {
        if ($this->null AND empty($value))
        {
            $value = NULL;
        }

        $value = $this->default;
    }
   die("Found?: {$found}  <br /> Original Value is: {$original_value }  <br /> Value now is: {$value}");
   return $value;
}
</pre>

**\* output: ***

<pre>
Found: no
Original Value: 1
Value now is: NULL
</pre>


this how i found that the value being pass is the key and not the value even if you make use of a 1 dim array thats why i think instead of using in_array() it should be array_key_exists() this will work for both 1 and 2 dim arrays

Thanks guys

**Comment by banks** [comment]
@ginad: this is strange. Look at the docs for `in_array()`, it **definitely** works on the values of the array not the keys. My guess is this is a red herring and actually the bug is elsewhere. In you `set()` method above can you call `var_dump($this->choices)` and post the output?

Or perhaps I've misunderstood? The value passed in is the value you set for the field surely - that is how all Jelly fields work. This value is expected to match one of the option _values_ so in_array() should work fine. There is something more subtle going on and I',m surprised because we have unit tests that show this feature to work as we expect.

The fact that original value is 1 is clearly the cause of the problem. How are you setting the field value and with precisely what code?

**Comment by ginad** [comment]
I make use of the input function in jelly.

ex. 
**\* model user ***

<pre>
...
$gender = new Field_Enum(array(
 "choices"=> array("male","female","others"),
 'label'=>"Gender: ",
 'default'=>NULL,
 "rules"=>array("not_empty"=>NULL)
))
...
</pre>


**\* controller ***

<pre>
public function new(){
 $j = Model::factory("user");
 $v = View::factory("new_user");
 if($_POST){
   $j->set($_POST);
   try{
     $j->save();
     ....
   }catch(Exception $e){
   die($e->array->errors("users"));
  }
 }
 $v->j = $j;
}
</pre>

**\* view new_user ***

<pre>
$j->input("gender")->label <br />
$j->input("gender");
</pre>


output of the var_dump($this->choices) is:

<pre>
array(3) { [0]=> string(4) "male" [1]=> string(6) "female" [2]=> string(6) "others" }
</pre>


when i choose "male" the $value in set() is 0 and if I choose "female", $value is 1 and if "others" value is 2

so what the set function is doing in checking if 0 ,1 or 2 are in array "male","female","others" so it keeps returning $this->default which is NULL

**Comment by banks** [comment]
Ah, this is a bug caused by the input HTML assuming the choices are Key value (because I wrote that HTML and Jon wrote the handling logic).

We need to decide whether we will use key => value or flat values. I think we should change the choices to Key value otherwise generating a readable select dropdown is a bit of a nightmare. If could be argued that it is not the job of the Field data type to define the labesl in the select though.

Jon this is up to you. If you want the enum choices should sty the same, we just need to change the input template to reflect that.

@ginad: the field does actually work as expected, just the genrated HTML doesn't.
