### ISSUE TITLE
Overruling order_by isn't possible [it is but is broken? Needs testing]

### ISSUE THREAD

**Issue by glamorous** [jonathangeiger/kohana-jelly#89]
When I want to sort differently then default set in my model, it doesn't matter, he doesn't overrule a thing.. Don't know if it's already possible or not but it should be nice if you can extend it too...

If more information is needed, just shoot! :)

**Comment by banks** [comment]
Yeah I've thought about this before but it's hard to know how to get around it neatly. We will probably need to have a way to supress the default ordeing. Maybe something like:

```
Jelly::select('posts')->order_by('field', 'direction', TRUE);
```

Where the third param overrides any current ordering clauses.

**Comment by SpadXIII** [comment]
I misread the question and banks was quicker to reply

@banks: how could the default ordering be cleared completely? Or multiple calls to `order_by` with the third parameter being `TRUE` ? That would probably clear out any previous ordering. Only the last order_by would be set.

**Comment by banks** [comment]
TRUE would wipeout all order_by clauses. Anything else is just confusing. I think it is a huge edge case that you would want to change only the last tiebreaker of the ordering claus in some situations.

**Comment by glamorous** [comment]
You could check in "_build ( )" if the array has duplicates for the keys? Only able to override "one", not the whole thing?

I just looked at the code and the comment in "_build()" is confusing

```
 // Don't add default sorting if order_by() has been set manually
```

Looks like this line is not doing his job :s

```
if ($this->_meta AND ! count($this->_order_by))
```

What I think is happening (just by following the code, not yet tested) with the order_by array is:

```
// Manual set in the query:
array(
    0 => array('date', 'ASC'),
    1 => array('title' => 'ASC'),
)

// After loading the defaults:
array(
    0 => array('date', 'ASC'),
    1 => array('title' => 'ASC'),
    2 => array('date', 'DESC'),
 )
```

If this is actually what's happening, we should find a solution to look for duplicates and delete the last occurence...

**Comment by SpadXIII** [comment]
Looking for duplicates alone won't fix every option though. What if you want to order by a different column than the default?
The default could be `order_by('date', 'DESC');` which you could want to override by ordering in `creation_date`. This would have 2 order_by-items but no duplicates?

**Comment by glamorous** [comment]
Good point :) A probably (bad) solution could be to have a new method "order_by_array" that's pretty same as "->sorting()" in meta... where you provide an array of all the order_by's with an extra parameter to exclude the defaults or not...

(Just thinking out loud)

**Comment by SpadXIII** [comment]
If using banks' idea, you could override the sorting like this:

```
Jelly::select('posts')
    ->order_by('field1', 'direction', TRUE)
    ->order_by('field2', 'direction')
    ->order_by('field3', 'direction');
```

Only the first order_by should contain the 3rd parameter (`TRUE`) as you want to clear any sorting before that.

But I think you do have a point about that comment in the Jelly code. I only briefly looked at the part, but don't have enough time (yet) to take a better look.

**Comment by banks** [comment]
> What I think is happening (just by following the code, not yet tested) with the order_by array is:

Not quite right.

The code in there at the moment I put in to fix this (just remembered now you post it!). Since the defaults don't get added till the query executes, I have included the logic that if you have manually called `order_by()` in your query, the defaults are ignored. This was an attempt to resolve this issue and I'd forgotten I'd done it earlier!

I think this is a good solution. I really can't see a good reason to have multiple default sorting columns and then need granular control over exactly which ones are overridden in a specific case. That is just too complex. The way it works now (now that I remember my little fix above) is as follows:

```
// Sorting in model is set to array('date', 'ASC')
Jelly::select('post')->execute(); // will be sorted by default (date)

Jelly::select('post')->order_by('title', 'DESC')->execute(); // Will be sorted ONLY by title
```

If you really have such complex needs for sorting that you end up with many order_by statements, you should implement your own logic to manage them. it feels like too much of an edge case to provide granular control of this stuff - you might as well just do it manually every time and have no default if your model is that complex.

I'll close this since this issue is actually as fixed as we want it for now by my code pointed out above - I'd forgotten I did that! If what I have described doesn't actually work, let us know and we will re-open this to fix the bug.

**Comment by glamorous** [comment]
Well... I suppose it isn't working, that's the reason I opened this issue in the first place... Is there already a jelly-unit-test for this?

The solution you provided is great, but I thought it wasn't working... If it's working, I must check my code again where I'am wrong...

**Comment by banks** [comment]
> Is there already a jelly-unit-test for this?

The unit tests cover this. not sure if it is directly tested though. It should be.

Will re-open until we have added a specific test although I thought I had verified this logic worked. If you have an example where it doesn't please post.

**Comment by glamorous** [comment]
Will test this tonight (not unit-test, but live-test :-) )

If it fails: I will post my code

**Comment by glamorous** [comment]
Everything works fine. I think my problem was also with using key => value pairs...
